config/routes.rb
Postman::Engine.routes.draw do

  resources :mail_servers do
    member do
      get :test
      post :send_test
    end
  end

  resources :letter_templates

  root to: 'mail_servers#index'
end

app/models/postman/asset.rb
module Postman
  class Asset < ActiveRecord::Base
    # attr_accessible :title, :body
  end
end

app/models/postman/letter_template.rb
module Postman
  class LetterTemplate < ActiveRecord::Base
    attr_accessible :html_content, :name, :text_content
    validates :name, :html_content, :text_content, presence: true

    def letter_variables
      [
       html_content.to_s.
       scan(/{{?[^}}]*}}/).map{|j| j.gsub(/}}|{{/, '').gsub(/#|\^|\/|=|!|<|>|&|\{/, '') }.uniq.select{ |j| j !~ /^attachments/},

       text_content.to_s.
       scan(/{{?[^}}]*}}/).map{|j| j.gsub(/}}|{{/, '').gsub(/#|\^|\/|=|!|<|>|&|\{/, '') }.uniq.select{ |j| j !~ /^attachments/}
      ].flatten.uniq
    end

  end
end

app/models/postman/mail_server.rb
module Postman
  class MailServer < ActiveRecord::Base
    attr_accessible :name, :delivery_method, :address, :port, :domain, :user_name, :password, :authentication, :enable_starttls_auto
    store :settings, accessors: [
                                 :address, :port, :domain,
                                 :user_name, :password, :authentication, :enable_starttls_auto
                                ]

    validates :name, presence: true, uniqueness: true
    validates :name, :delivery_method, :settings, presence: true
    validates :user_name, :password, :address, :port, :domain,
              :authentication, :enable_starttls_auto, presence: true, :if => proc{ |t| t.delivery_method.to_s == 'smtp' }


    def test(to_address)
      Pony.mail({
                  :from => "postman@postman.com",
                  :subject => "[ POSTMAN ] test",
                  :body => "TEST: text body",
                  :html_body => "<h2>TEST</h2>:<br /> html body",
                  :to => to_address,
                  :via => delivery_method.to_sym,
                  :via_options => settings
                })
    end

  end
end

app/controllers/postman/application_controller.rb
module Postman
  class ApplicationController < ActionController::Base
  end
end

app/controllers/postman/letter_templates_controller.rb
require_dependency "postman/application_controller"

module Postman
  class LetterTemplatesController < ApplicationController
    inherit_resources
  end
end

app/controllers/postman/mail_servers_controller.rb
require_dependency "postman/application_controller"

module Postman
  class MailServersController < ApplicationController
    inherit_resources

    def new
      new! do
        if params[:template].to_s == 'gmail'
          resource.address = 'smtp.gmail.com'
          resource.port = '587'
          resource.authentication = 'plain'
          resource.enable_starttls_auto = true
          resource.domain = 'localhost.localdomain'
        end

      end
    end

    def send_test
      if params[:email].present?
        resource.test(params[:email])
        redirect_to mail_servers_path, :notice => "OK"
      else
        redirect_to :back, :alert => "Email must not be blank"
      end
    end

  end
end

app/helpers/postman/application_helper.rb
module Postman
  module ApplicationHelper
  end
end

app/helpers/postman/letter_templates_helper.rb
module Postman
  module LetterTemplatesHelper
  end
end

app/helpers/postman/mail_servers_helper.rb
module Postman
  module MailServersHelper
  end
end

app/views/layouts/postman/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/postman/_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Postman", root_path, class: "brand"
      .container.nav-collapse
        %ul.nav
          %li.divider-vertical
          %li= link_to t('mailers'), '#'
          %li= link_to t('templates'), letter_templates_path
          %li.divider-vertical
          %li= link_to t('mail_servers'), mail_servers_path

app/views/layouts/postman/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Postman"
      %meta{:content => content_for?(:description) ? yield(:description) : "Postman", :name => "description"}
        = stylesheet_link_tag "postman/application", :media => "all"
        = javascript_include_tag "postman/application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/postman/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/postman/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/postman/letter_templates/_form.html.haml
= form.input :name, :input_html => {:class => "input-xxlarge"}

%hr
.row-fluid
  %div.control-group{:style => "height: 650px;"}
    %legend
      HTML Content
    = form.text_area :html_content, :cols => 100, :rows => 5, :class => "input-xxlarge", :style => "width: 100%; height: 400px;"
    #html_editor.content_editor

.row-fluid
  %div.control-group{:style => "height: 650px;"}
    %legend
      TEXT Content
    = form.text_area :text_content, :cols => 100, :rows => 5, :class => "input-xxlarge", :style => "width: 100%; height: 400px;"
    #text_editor.content_editor

  :css
    .content_editor {
    width: 88%; height: 600px;
    }

  :javascript
    $(function(){
    var html_editor = ace.edit("html_editor");
    html_editor.setTheme("ace/theme/twilight");
    var HTMLMode = require("ace/mode/html").Mode;
    html_editor.getSession().setMode(new HTMLMode());

    var html_textarea = $('#letter_template_html_content').hide();
    html_editor.getSession().setValue(html_textarea.val());
    html_editor.getSession().on('change', function(){  html_textarea.val(html_editor.getSession().getValue());  });


    var text_editor = ace.edit("text_editor");
    text_editor.setTheme("ace/theme/twilight");
    var TEXTMode = require("ace/mode/text").Mode;
    text_editor.getSession().setMode(new TEXTMode());

    var text_textarea = $('#letter_template_text_content').hide();
    text_editor.getSession().setValue(text_textarea.val());
    text_editor.getSession().on('change', function(){  text_textarea.val(html_editor.getSession().getValue());  });

    });

app/views/postman/letter_templates/index.html.haml
.row-fluid
  .span10
    %h4
      Templates
  .span2
    = link_to "New", new_letter_template_path, :class => "btn btn-small"

.row-fluid
  .span12

    %table.table.table-bordered.table-striped
      %thead
        %tr
          %th Name
          %th
      %body
        - collection.each do  |item|
          %tr
            %td
              = link_to item.name, letter_template_path(item)
            %td

              .btn-group
                = link_to "Test", "test_letter_template_path(item)", :class => "btn  btn-small"
                = link_to "Attachments","letter_template_assets_path(item)", :class => "btn btn-small"
                = link_to "Edit Content", "content_letter_template_path(item)", :class => "btn btn-small"
              .btn-group
                = link_to "Edit", edit_letter_template_path(item), :class => "btn btn-small"
                = link_to letter_template_path(item), :class => "btn btn-small", :method => :delete, :confirm => "Yes?" do
                  %i.icon-trash
                  Delete

app/views/postman/letter_templates/new.html.haml
.row-fluid
  .span12
    = simple_form_for(resource, :html => {:class => "form-horizontal"}) do |form|
      %legend
        New Template
      = render form
      = form.button :submit, t("views.common.save")
      = link_to t(".cancel"), :back, :class => "btn btn-link"

app/views/postman/mail_servers/.#test.html.haml
maxim@wiseQaa.4708:1353739429

app/views/postman/mail_servers/_form.html.haml
= form.input :name, :input_html => {:class => "input-xxlarge"}
= form.input :delivery_method, :as => :select, :collection => [:smtp,:sendmail, :file ], :include_blank => false
%legend
  Settings
= form.input :address, :input_html => {:class => "input-xlarge"}
= form.input :port, :input_html => {:class => "input-xlarge"}
= form.input :domain, :input_html => {:class => "input-xlarge"}
= form.input :user_name, :input_html => {:class => "input-xlarge"}
= form.input :password, :input_html => {:class => "input-xlarge"}, :as => :string
= form.input :authentication, :as => :select, :collection => [:plain, :login, :cram_md5]
= form.input :enable_starttls_auto, :as => :select, :collection => [true, false]

app/views/postman/mail_servers/edit.html.haml
.row-fluid
  .span1
  .span10
    = simple_form_for(resource, :html => {:class => "form-horizontal"}) do |form|
      %legend
        Edit Server
      = render form
      = form.button :submit, t("views.common.save")
      = link_to t(".cancel"), :back, :class => "btn btn-link"
  .span1

app/views/postman/mail_servers/index.html.haml
.row-fluid
  .span10
    %h4
      Mail Servers
  .span2
    .btn-group
      = link_to new_mail_server_path, :class => "btn btn-small dropdown-toggle", :data => {:toggle => 'dropdown'} do
        Add new
        %span.caret
      %ul.dropdown-menu
        %li= link_to 'Add new', new_mail_server_path, :class => "btn-small"
        %li= link_to 'Add new (gmail)', new_mail_server_path(:template => :gmail), :class => "btn-small"

.row-fluid
  .span12

    %table.table.table-bordered.table-striped
      %thead
        %tr
          %th Name
          %th
      %body
        - collection.each do  |item|
          %tr
            %td
              %i.icon-globe
              = item.name
            %td
              .btn-group
                = link_to "Test", test_mail_server_path(item), :class => "btn btn-small"
              .btn-group
                = link_to "Edit",edit_mail_server_path(item), :class => "btn btn-small"
                = link_to mail_server_path(item), :class => "btn btn-small", :method => :delete, :confirm => "Yes?" do
                  %i.icon-trash
                  Delete

app/views/postman/mail_servers/new.html.haml
.row-fluid
  .span1
  .span10
    = simple_form_for(resource, :html => {:class => "form-horizontal"}) do |form|
      %legend
        New server
      = render form
      = form.button :submit, t("views.common.save")
      = link_to t(".cancel"), :back, :class => "btn btn-link"
  .span1

app/views/postman/mail_servers/test.html.haml
.row
  .span2
    Test Mail Servert
.row-fluid
  .span1
  .span10
    = simple_form_for(resource, :url => send_test_mail_server_path(resource), :html => {:class => "form-horizontal", :method => :post}) do |form|
      .control-group.string
        %label.string.control-label
          Email
        .controls
          = text_field_tag :email, "", :class => "input-xlarge"
      %hr
      %button.m-btn.blue-stripe
        = t("views.common.send")
      = link_to t(".cancel"), mail_servers_path, :class => "btn-link"
  .span1
%hr
.row-fluid
  .span2
    Settings
  .span10
    - resource.settings.each do |k,v|
      %ul
        %li
          = " #{k} : #{v}"